//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciNotMVCProjesi.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOgrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblOgrenciler()
        {
            this.TblNotlar = new HashSet<TblNotlar>();
        }
    
        public short OgrenciID { get; set; }
        public string OgrenciAd { get; set; }
        public string OgrenciSoyad { get; set; }
        public string OgrenciFotograf { get; set; }
        public string OgrenciCinsiyet { get; set; }
        public Nullable<byte> OgrenciKulup { get; set; }
    
        public virtual TblKulupler TblKulupler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblNotlar> TblNotlar { get; set; }
    }
}
